config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:show, :edit, :update, :index, :new] do
    resources :infos
    resources :card_infos, only: [:new, :show, :destroy] do
      collection do
        post 'show', to: 'card_infos#show'
        post 'pay', to: 'card_infos#pay'
      end
    end
  end

  root 'items#index'
  resources :items do
    resources :transactions, only: [:new, :order_status] do
      collection do
        get 'new', to: 'transactions#new'
        get 'pay', to: 'transactions#pay'
        get 'done', to: 'transactions#done'
        get 'order_status', to: 'transactions#order_status'
        get 'order_status_ship', to: 'transactions#order_status_ship'
        get 'order_status_receive', to: 'transactions#order_status_receive'

      end
    end
  end
  # 仮置き
  resources :listings, only: [:index] do
    collection do
      get 'in_progress', to: 'listings#in_progress'
      get 'completed', to: 'listings#completed'
      get 'purchase', to: 'listings#purchase'
      get 'purchased', to: 'listings#purchased'
    end
  end



  get 'logout', to: 'users#logout_form'
end

app/models/card_info.rb
class CardInfo < ApplicationRecord
  belongs_to :user
end

app/controllers/card_infos_controller.rb
class CardInfosController < ApplicationController
  require "payjp"

  def new
    card = CardInfo.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params[:payjp_token].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(card: params[:payjp_token])
      @card = CardInfo.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def destroy #PayjpとCardデータベースを削除します
    card = CardInfo.where(user_id: current_user.id).first
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    customer = Payjp::Customer.retrieve(card.customer_id)
    customer.delete
    card.delete
    redirect_to action: "show"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    @card = CardInfo.where(user_id: current_user.id).first
    if @card.blank?
      render "show"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
      @card_brand = @default_card_information.brand #カード会社のブランドアイコンを表示
      case @card_brand
      when "Visa"
        @card_src = "visa.svg"
      when "JCB"
        @card_src = "jcb.svg"
      when "MasterCard"
        @card_src = "master-card.svg"
      when "American Express"
        @card_src = "american_express.svg"
      when "Diners Club"
        @card_src = "dinersclub.svg"
      when "Discover"
        @card_src = "discover.svg"
      end
    end
  end
end

app/helpers/card_infos_helper.rb
module CardInfosHelper
end

app/views/card_infos/_cardBlank.html.haml
/クレジットカード情報がない場合の画面
.content
  .content__credit
    %h2.credit-head
      ="支払い方法"
    .credit-inner
      %section
        .credit-content
          .sub-credit-head
            ="クレジットカード一覧"
        .payment-content
          .add-payment
            .add-payment-content
              .form-group
                .btn-default
                  = link_to new_user_card_info_path, class: "btn-default btn-red" do
                    %i.fa.fa-credit-card
                    クレジットカードを追加する

app/views/card_infos/_cardExist.html.haml
/クレジットカード情報がある場合の画面 カード情報を表示
.content
  .content__credit
    %h2.credit-head
      ="支払い方法"
    .credit-inner
      %section
        .credit-content
          .sub-credit-head
            ="クレジットカード一覧"
        .payment-content
          %ul
            %li
              .payment-inside
                = image_tag "#{@card_src}", size: "34x20", alt: @card_brand, class: ".image"
                .payment-num
                  = "**** **** **** " + @default_card_information.last4
                .payment-num
                  - exp_month = @default_card_information.exp_month.to_s
                  - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                  = exp_month + " / " + exp_year
                = link_to "削除する", user_card_info_path, method: :delete, class: "button payment-remove"

          .setting-register
            .setting-register-block
              .payment-notice
                ="支払い方法について"
                %i.fa.fa-angle-right

app/views/card_infos/new.html.haml
/クレジットカード情報入力
#wrapper
  =render 'layouts/header'
  =render 'layouts/breadCrumbs'
  .mypage-main
    .content
      .content__credit
        %h2.credit-head
          ="クレジットカード情報入力"
        = form_with url: {controller: "card_infos", action: "pay"}, id: "charge-form", name: "inputForm", class: "credit-inner" do |f|
          .credit-content
            .credit-form-group
              = f.label :カード番号 do
                = "カード番号"
                .credit-form-must
                  ="必須"
              = f.text_field :number, id: "payment_card_no", class: 'number credit-input', placeholder: '半角数字のみ'
              %ul.card-list
                %li.card-list-item
                  = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg", size: "49x20", class: ".image"
                %li.card-list-item
                  = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg", size: "34x20", class: ".image"
                %li.card-list-item
                  = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg", size: "30x20", class: ".image"
                %li.card-list-item
                  = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg", size: "32x20", class: ".image"
                %li.card-list-item
                  = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg", size: "21x20", class: ".image"
                %li.card-list-item
                  = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg", size: "32x20", class: ".image"
                %li.card-list-item
                  = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg", size: "32x20", class: ".image"
            .credit-form-group
              = f.label :有効期限 do
                = "有効期限"
                .credit-form-must
                  ="必須"
              .credit-select
                %ul
                  %li
                    = f.select :exp_month, [["--",],["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{}, {id: "payment_card_expire_mm", class: "exp_month credit-month-input"}
                    = fa_icon 'angle-down', class: 'credit-arrow-down'
                  %li
                    ="月"
                %ul
                  %li
                    = f.select :exp_year, [["--",],["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]], {}, {id: "payment_card_expire_yy", class: "exp_year credit-month-input"}
                    = fa_icon 'angle-down', class: 'credit-arrow-down'
                  %li
                    ="年"
            .credit-form-group
              = f.label :セキュリティコード do
                = "セキュリティコード"
                .credit-form-must
                  ="必須"
              = f.text_field :cvc, id: "payment_card_cvc", class: 'credit-input cvc', placeholder: 'カード背面4桁もしくは3桁の番号'
              .signup-code
                %span.credit-question ?
                .credit-note
                  ="カード裏面の番号とは？"
            .form-group
              .btn-default
                = f.submit :追加する, id: "submit-button", class: "btn-default btn-red"

    =render "layouts/sidemenu"

  =render "layouts/footer"

app/views/card_infos/show.html.haml
/クレジットカード情報をある場合とない場合で表示
#wrapper
  = render 'layouts/header'
  = render 'layouts/breadCrumbs'
  .mypage-main
    - if @card.blank?
      = render 'cardBlank'
    - else
      = render 'cardExist'
      
    = render "layouts/sidemenu"
  = render "layouts/footer"