config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:show, :edit, :update, :index, :new] do
    resources :infos
    resources :card_infos, only: [:new, :show, :destroy] do
      collection do
        post 'show', to: 'card_infos#show'
        post 'pay', to: 'card_infos#pay'
      end
    end
  end

  root 'items#index'
  resources :items do
    resources :transactions, only: [:new, :order_status] do
      collection do
        get 'new', to: 'transactions#new'
        get 'pay', to: 'transactions#pay'
        get 'done', to: 'transactions#done'
        get 'order_status', to: 'transactions#order_status'
        get 'order_status_ship', to: 'transactions#order_status_ship'
        get 'order_status_receive', to: 'transactions#order_status_receive'

      end
    end
  end
  # 仮置き
  resources :listings, only: [:index] do
    collection do
      get 'in_progress', to: 'listings#in_progress'
      get 'completed', to: 'listings#completed'
      get 'purchase', to: 'listings#purchase'
      get 'purchased', to: 'listings#purchased'
    end
  end



  get 'logout', to: 'users#logout_form'
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    # before_action :require_signin
  def index
    @items = Item.where(user_id: current_user.id, trade_status: 1).limit(3).order("created_at DESC")
  end

  def in_progress
    @reserveditems = Item.where(user_id: current_user.id, trade_status: 2).limit(5).order("created_at DESC")
    @shippeditems = Item.where(user_id: current_user.id, trade_status: 3).limit(5).order("created_at DESC")
  end

  def completed
    @items = Item.where(user_id: current_user.id, trade_status: 4).limit(10).order("created_at DESC")
  end

  def purchase
    @purchaseitems = Item.where(buyer_id: current_user.id, trade_status: 2).limit(5).order("created_at DESC")
    @purchaseditems = Item.where(buyer_id: current_user.id, trade_status: 3).limit(5).order("created_at DESC")
  end

  def purchased
    @items = Item.where(buyer_id: current_user.id, trade_status: 4).limit(10).order("created_at DESC")
  end

end

app/views/listings/completed.html.haml
.mypage-headder
  =render"layouts/header"
  =render"layouts/breadCrumbs"
.mypage-main
  .content
    .content__listing-box
      出品した商品
      .content__listing-box__menu
        = link_to listings_path do
          .content__listing-box__menu__side 出品中
        = link_to in_progress_listings_path do
          .content__listing-box__menu__side 取引中
        = link_to completed_listings_path do
          .content__listing-box__menu__now 売却済み
      - if @items.present?
        - @items.each do |item|
          = link_to item_path(item.id) do
            .content__listing-box__item-tab__box
              = image_tag item.images[0].image.url,size:"50x50", class: 'content__listing-box__item-tab__box__icon'
              .content__listing-box__item-tab__box__info= item.name
              %i.fa.fa-chevron-right.arrowi
      - else
        .content__listing-box__item-tab
          .content__listing-box__item-tab__image-box
          .content__listing-box__item-tab__image
          .content__listing-box__item-tab__text 出品中の商品がありません

      .content__listing-box__pager-box
        = link_to do
          .content__listing-box__pager-box__prev
            %i.fa.fa-chevron-left.prev
        = link_to do
          .content__listing-box__pager-box__next
            %i.fa.fa-chevron-right.next
            
  =render "layouts/sidemenu"
  =render "layouts/btn"
.mypage-footer
  =render"layouts/footer"

app/views/listings/in_progress.html.haml
.mypage-headder
  =render"layouts/header"
  =render"layouts/breadCrumbs"
.mypage-main
  .content
    .content__listing-box
      出品した商品
      .content__listing-box__menu
        = link_to listings_path do
          .content__listing-box__menu__side 出品中
        = link_to in_progress_listings_path do
          .content__listing-box__menu__now 取引中
        = link_to completed_listings_path do
          .content__listing-box__menu__side 売却済み
      - if @reserveditems.present?
        - @reserveditems.each do |item|
          = link_to order_status_item_transactions_path(item.id) do
            .content__listing-box__item-tab__box
              = image_tag item.images[0].image.url,size:"50x50", class: 'content__listing-box__item-tab__box__icon'
              .content__listing-box__item-tab__box__info= item.name
              %i.fa.fa-chevron-right.arrowi
      - if @shippeditems.present?
        - @shippeditems.each do |item|
          = link_to order_status_item_transactions_path(item.id) do
            .content__listing-box__item-tab__box
              = image_tag item.images[0].image.url,size:"50x50", class: 'content__listing-box__item-tab__box__icon'
              .content__listing-box__item-tab__box__info= item.name
              %i.fa.fa-chevron-right.arrowi
      - if @reserveditems.empty? && @shippeditems.empty?
        .content__listing-box__item-tab
          .content__listing-box__item-tab__image-box
          .content__listing-box__item-tab__image
          .content__listing-box__item-tab__text 出品中の商品がありません

      .content__listing-box__pager-box
        = link_to do
          .content__listing-box__pager-box__prev
            %i.fa.fa-chevron-left.prev
        = link_to do
          .content__listing-box__pager-box__next
            %i.fa.fa-chevron-right.next
            
  =render "layouts/sidemenu"
  =render "layouts/btn"
.mypage-footer
  =render"layouts/footer"

app/views/listings/index.html.haml
.mypage-headder
  =render"layouts/header"
  =render"layouts/breadCrumbs"
.mypage-main
  .content
    .content__listing-box
      出品した商品
      .content__listing-box__menu
        = link_to listings_path do
          .content__listing-box__menu__now 出品中
        = link_to in_progress_listings_path do
          .content__listing-box__menu__side 取引中
        = link_to completed_listings_path do
          .content__listing-box__menu__side 売却済み
      - if @items.present?
        - @items.each do |item|
          = link_to item_path(item.id) do
            .content__listing-box__item-tab__box
              = image_tag item.images[0].image.url,size:"50x50", class: 'content__listing-box__item-tab__box__icon'
              .content__listing-box__item-tab__box__info= item.name
              %i.fa.fa-chevron-right.arrowi
      - else
        .content__listing-box__item-tab
          .content__listing-box__item-tab__image-box
          .content__listing-box__item-tab__image 
          .content__listing-box__item-tab__text 出品中の商品がありません

      .content__listing-box__pager-box
        = link_to do
          .content__listing-box__pager-box__prev
            %i.fa.fa-chevron-left.prev
        = link_to do
          .content__listing-box__pager-box__next
            %i.fa.fa-chevron-right.next
            
  =render "layouts/sidemenu"
  =render "layouts/btn"
.mypage-footer
  =render"layouts/footer"

app/views/listings/purchase.html.haml
.mypage-headder
  =render"layouts/header"
  =render"layouts/breadCrumbs"
.mypage-main
  .content
    .content__listing
      .content__listing__head 購入した商品
      .content__listing__tubs
        = link_to purchase_listings_path do
          .content__listing__tubs__now 取引中
        = link_to purchased_listings_path do
          .content__listing__tubs__side 過去の取引
      - if @purchaseitems.present?
        - @purchaseitems.each do |item|
          = link_to order_status_item_transactions_path(item.id) do
            .content__listing-box__item-tab__box
              = image_tag item.images[0].image.url,size:"50x50", class: 'content__listing-box__item-tab__box__icon'
              .content__listing-box__item-tab__box__info= item.name
              %i.fa.fa-chevron-right.arrowi
      - if @purchaseditems.present?
        - @purchaseditems.each do |item|
          = link_to order_status_item_transactions_path(item.id) do
            .content__listing-box__item-tab__box
              = image_tag item.images[0].image.url,size:"50x50", class: 'content__listing-box__item-tab__box__icon'
              .content__listing-box__item-tab__box__info= item.name
              %i.fa.fa-chevron-right.arrowi
      - if @purchaseitems.empty? && @purchaseditems.empty?
        .content__listing-box__item-tab
          .content__listing-box__item-tab__image-box
          .content__listing-box__item-tab__image 
          .content__listing-box__item-tab__text 出品中の商品がありません
            
  =render "layouts/sidemenu"
  =render "layouts/btn"
.mypage-footer
  =render"layouts/footer"

app/views/listings/purchased.html.haml
.mypage-headder
  =render"layouts/header"
  =render"layouts/breadCrumbs"
.mypage-main
  .content
    .content__listing
      .content__listing__head 購入した商品
      .content__listing__tubs
        = link_to purchase_listings_path do
          .content__listing__tubs__side 取引中
        = link_to purchased_listings_path do
          .content__listing__tubs__now 過去の取引
      - if @items.present?
        - @items.each do |item|
          = link_to item_path(item.id) do
            .content__listing-box__item-tab__box
              = image_tag item.images[0].image.url,size:"50x50", class: 'content__listing-box__item-tab__box__icon'
              .content__listing-box__item-tab__box__info= item.name
              %i.fa.fa-chevron-right.arrowi
            
      - else
        .content__listing-box__item-tab
          .content__listing-box__item-tab__image-box
          .content__listing-box__item-tab__image 
          .content__listing-box__item-tab__text 出品中の商品がありません
            
  =render "layouts/sidemenu"
  =render "layouts/btn"
.mypage-footer
  =render"layouts/footer"