config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:show, :edit, :update, :index, :new] do
    resources :infos
    resources :card_infos, only: [:new, :show, :destroy] do
      collection do
        post 'show', to: 'card_infos#show'
        post 'pay', to: 'card_infos#pay'
      end
    end
  end

  root 'items#index'
  resources :items do
    resources :transactions, only: [:new, :order_status] do
      collection do
        get 'new', to: 'transactions#new'
        get 'pay', to: 'transactions#pay'
        get 'done', to: 'transactions#done'
        get 'order_status', to: 'transactions#order_status'
        get 'order_status_ship', to: 'transactions#order_status_ship'
        get 'order_status_receive', to: 'transactions#order_status_receive'

      end
    end
  end
  # 仮置き
  resources :listings, only: [:index] do
    collection do
      get 'in_progress', to: 'listings#in_progress'
      get 'completed', to: 'listings#completed'
      get 'purchase', to: 'listings#purchase'
      get 'purchased', to: 'listings#purchased'
    end
  end



  get 'logout', to: 'users#logout_form'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  require "payjp"

  before_action :move_to_sign_in
  before_action :set_item, only: [:order_status, :order_status_ship, :order_status_receive]
  before_action :set_buyerinfo, only: [:order_status]

  def new
    @item = Item.find(params[:item_id])
    @card = CardInfo.where(user_id: current_user.id).first
    #CardInfoテーブルからpayjpの顧客IDを検索
    if @card.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to new_user_card_info_path(user_id: current_user.id)
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(@card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(@card.card_id)
      @card_brand = @default_card_information.brand #カード会社のブランドアイコンを表示
      case @card_brand
      when "Visa"
        @card_src = "visa.svg"
      when "JCB"
        @card_src = "jcb.svg"
      when "MasterCard"
        @card_src = "master-card.svg"
      when "American Express"
        @card_src = "american_express.svg"
      when "Diners Club"
        @card_src = "dinersclub.svg"
      when "Discover"
        @card_src = "discover.svg"
      end
    end
  end

  def pay
    @item = Item.find(params[:item_id])
    card = CardInfo.where(user_id: current_user.id).first
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    Payjp::Charge.create(
      amount: @item.price, #支払金額を入力
      customer: card.customer_id, #顧客ID
      currency: 'jpy', #日本円
    )
    @item.update(purchase_params)
    redirect_to root_path, notice: "購入が完了しました" #完了画面に移動
    rescue => e
      redirect_to root_path, notice: "失敗しました"
  end

  def order_status
    @fee = (@item.price * 0.1).ceil
    @profit = @item.price - @fee
  end

  def order_status_ship
    if @item.present?
      @item.update(shipped_params) 
      redirect_to in_progress_listings_path
    else
      redirect_to root_path
    end
  end

  def order_status_receive
    if @item.present?
      @item.update(received_params) 
      redirect_to purchased_listings_path
    else
      redirect_to root_path
    end
  end

  private

  def move_to_sign_in
    redirect_to new_user_session_path unless user_signed_in?
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

  def set_buyerinfo
    @buyer = User.find(@item.buyer_id)
  end

  def purchase_params
    params.permit(:trade_status, :buyer_id).merge(trade_status: '2', buyer_id: current_user.id)
  end

  def shipped_params
    params.permit(:trade_status).merge(trade_status: '3' )
  end

  def received_params
    params.permit(:trade_status).merge(trade_status: '4' )
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_in-review.html.haml
.status__box
  .status__box__head 取引画面 
  .status__box__message
    .status__box__message__alart
      %i.fa.fa-truck
      .span 受取票待ち
    %p 商品が発送されました。受け取り評価をお待ちください。

app/views/transactions/_received.html.haml
.status__box
  .status__box__head 取引画面
  .status__box__message
    .status__box__message__alart
      %i.fa.fa-truck
      .span 受取完了報告をしてください
    %p 商品が発送されました。商品が到着したら、受取完了ボタンを押してください。
.status__box__button
  = link_to order_status_receive_item_transactions_path do
    .status__box__button.red-btn 受取完了

app/views/transactions/_shipped.html.haml
.status__box
  .status__box__head 取引画面 
  .status__box__message
    .status__box__message__alart
      %i.fa.fa-truck
      .span 発送をしてください
    %p 商品が購入され支払いされました。商品の発送を行ってください。
.status__box__button
  = link_to order_status_ship_item_transactions_path do
    .status__box__button.red-btn 発送完了

app/views/transactions/_shipping.html.haml
.status__box
  .status__box__head 取引画面 
  .status__box__message
    .status__box__message__alart
      %i.fa.fa-truck
      .span 配送待ち
    %p 出品者からの発送待ちです。しばらくお待ちください。

app/views/transactions/new.html.haml
.solo-container
  =render "layouts/session-header"

  %main.solo-main
    %section.main-container
      %h2.main-container__head
        購入を確定しますか？
      %section.main-container__content
        .content-inner
          %h3.content-inner__image
            = image_tag @item.images[0].image.url
          %p.content-inner__name
            = @item.name
          %form(action="" class="buy-form")
            %p.price-ja
              = "¥" + number_with_delimiter(@item.price)
              %span.shopping-fee
                = @item.postage
            %ul.point
              %li.point-parent
                .point-parent-toggle
                  ポイントはありません
            %ul.price
              %li.buy-price
                .buy-price__cell
                  支払い金額
                .buy-price__cell
                  %span
                    = "¥" + number_with_delimiter(@item.price)
            = link_to "購入する", pay_item_transactions_path(@item.id), class: "btn-default"
                
      %section.main-container__user-info
        .user-info-inner
          %h3 配送先
          %address.user-info-inner__address
            = "〒" + "#{current_user.address.zipcord}"
            %br
            = "#{current_user.address.prefecture}" + "#{current_user.address.city}" + "#{current_user.address.address}" + "#{current_user.address.building_name}"
            %br
            = "#{current_user.last_name}" + "#{current_user.first_name}"
          %p.user-info-inner__text
          = link_to root_path, class: "user-info-inner__edit" do
            %span 変更する
            %i.fa.fa-angle-right
      %section.main-container__card-data
        .card-data-inner
          %h3
            支払い方法
          %p.card-data-inner__text
            = "**** **** **** " + @default_card_information.last4
            %br
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          = image_tag "#{@card_src}", width: "26", height: "20", alt: @card_brand
          %p
          = link_to user_card_info_path(@card.id, @current_user.id), class: "card-data-inner__edit" do
            %span 変更する
            %i.fa.fa-angle-right

  =render "layouts/session-footer"

app/views/transactions/order_status.html.haml
.mypage-headder
  =render"layouts/header"
  =render"layouts/breadCrumbs"
.mypage-main
  .content
    .status__container
      - if user_signed_in? && @item.trade_status == 2 && current_user.id == @item.user_id
        =render "transactions/shipped"

      - if user_signed_in? && @item.trade_status == 2 && current_user.id == @item.buyer_id
        =render "transactions/shipping"

      - if user_signed_in? && @item.trade_status == 3 && current_user.id == @item.user_id
        =render "transactions/in-review"
      
      - if user_signed_in? && @item.trade_status == 3 && current_user.id == @item.buyer_id 
        =render "transactions/received"
      
  - if user_signed_in? && current_user.id == @item.user_id
    =render "layouts/buyer-info"
  - if user_signed_in? && current_user.id == @item.buyer_id
    =render "layouts/exhibitor-info"
  =render "layouts/btn"
.mypage-footer
  =render"layouts/footer"