config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:show, :edit, :update, :index, :new] do
    resources :infos
    resources :card_infos, only: [:new, :show, :destroy] do
      collection do
        post 'show', to: 'card_infos#show'
        post 'pay', to: 'card_infos#pay'
      end
    end
  end

  root 'items#index'
  resources :items do
    resources :transactions, only: [:new, :order_status] do
      collection do
        get 'new', to: 'transactions#new'
        get 'pay', to: 'transactions#pay'
        get 'done', to: 'transactions#done'
        get 'order_status', to: 'transactions#order_status'
        get 'order_status_ship', to: 'transactions#order_status_ship'
        get 'order_status_receive', to: 'transactions#order_status_receive'

      end
    end
  end
  # 仮置き
  resources :listings, only: [:index] do
    collection do
      get 'in_progress', to: 'listings#in_progress'
      get 'completed', to: 'listings#completed'
      get 'purchase', to: 'listings#purchase'
      get 'purchased', to: 'listings#purchased'
    end
  end



  get 'logout', to: 'users#logout_form'
end

app/views/layouts/_breadCrumbs.html.haml
.bread-crumbs-body
  - case params.values_at :controller, :action

  - when ['users', 'show']
    - breadcrumb :user_show

  - when ['card_infos', 'show']# 支払い方法ページ
    - breadcrumb :card_info_show

  - when ['card_infos', 'new']# クレジットカード情報入力ページ
    - breadcrumb :card_info_new

  - when ['items', 'show']# 商品詳細ページ
    - breadcrumb :item_show, @item

  = breadcrumbs separator: " &nbsp;&nbsp;&#12297;&nbsp; ", class: "bread-crumbs", style: :ul

app/views/layouts/_btn.html.haml
%a.sell__btn{href: new_item_path}
  .sell__btn-text
    出品
  %i.fa.fa-camera.sell__btn-text-icon
  

app/views/layouts/_buyer-info.html.haml
.side
  .side__container
    %h3.transact-info-card 取引情報
    %table.transact-info-table
      %tr.white-record
        %th.transact-info-table-title
          商品
        %td.transact-info-table-display
          = link_to item_path(@item.id) do 
            = image_tag @item.images[0].image.url, size:"140x140"
            .item-name
              = @item.name
            .item-price
              = "¥" + "#{@item.price}"
      %tr.gray-record
        %th.transact-info-table-title
          送料
        %td
          = @item.postage
      %tr.white-record
        %th.transact-info-table-title
          販売手数料
        %td.transact-info-table-display
          = "¥" + "#@fee"
      %tr.gray-record
        %th.transact-info-table-title
          販売利益
        %td
          = "¥" + "#@profit"
      %tr.white-record
        %th.transact-info-table-title
          購入日
        %td.transact-info-table-display
          = @item.updated_at
      %tr.gray-record
        %th.transact-info-table-title
          商品ID
        %td
          = @item.id
      %th.transact-info-table-title
        お届け先
        %td.transact-info-table-display
          .zipcord
            = "〒" + "#{@buyer.address.zipcord}"
          .prefecture
            = "#{@buyer.address.prefecture}" + "#{@buyer.address.city}" + "#{@buyer.address.address}"
          .building
            = "#{@buyer.address.building_name}"
    
    
    %h3.transact-info-head 購入者情報
    %table.transact-info-table
      %tr.white-record
        %th.transact-info-table-title
          購入者
        %td.transact-info-table-display
          .buyer-icon
            = image_tag "member_photo_noimage_thumb.png", size: "60x60", class: ".image"
          .buyer-name
            = @buyer.nickname

app/views/layouts/_deletebtn.html.haml
.modal-wrapper#delete-modal
  .delete-modal
    .delete-modal__upper
      .delete-modal__upper__title 確認
      .delete-modal__upper__content 削除すると二度と復活できません。<br />削除する代わりに停止することもできます。<br /><br />本当に削除しますか？
    .delete-modal__under
      .delete-modal__under__left キャンセル
      .delete-modal__under__right
        = link_to item_path(@item.id), method: :delete do
          削除する

app/views/layouts/_exhibitor-info.html.haml
.side
  .side__container
    %h3.transact-info-card 取引情報
    %table.transact-info-table
      %tr.white-record
        %th.transact-info-table-title
          商品
        %td.transact-info-table-display
          = link_to item_path(@item.id) do 
            = image_tag @item.images[0].image.url, size:"140x140"
            .item-name
              = @item.name
            .item-price
              = "¥" + "#{@item.price}"
      %tr.gray-record
        %th.transact-info-table-title
          送料
        %td
          = @item.postage
      %tr.white-record
        %th.transact-info-table-title
          購入日
        %td.transact-info-table-display
          = @item.updated_at
      %tr.gray-record
        %th.transact-info-table-title
          商品ID
        %td
          = @item.id
      %th.transact-info-table-title
        お届け先
        %td.transact-info-table-display
          .zipcord
            = "〒" + "#{current_user.address.zipcord}"
          .prefecture
            = "#{current_user.address.prefecture}" + "#{current_user.address.city}" + "#{current_user.address.address}"
          .building
            = "#{current_user.address.building_name}"
    
    
    %h3.transact-info-head 出品者情報
    %table.transact-info-table
      %tr.white-record
        %th.transact-info-table-title
          出品者
        %td.transact-info-table-display
          .buyer-icon
            = image_tag "member_photo_noimage_thumb.png", size: "60x60", class: ".image"
          .buyer-name
            = "#{@item.user.nickname}"

app/views/layouts/_footer.html.haml
%aside.app__banner
  .app__banner__info
    .app__smartphone
      %img.app__smartphone-img{src: "https://www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?4194600336"}/
    .app__banner__info__inner
      %h2.app__banner__info__inner-msgapp
        スマホでかんたんフリマアプリ
      %p.app__banner__info__inner-download
        今すぐ無料ダウンロード！
      .app__banner__icon
        .app__banner__icon__mercari__icon
          %img.app__banner__icon__mercari__icon-picture{src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?4194600336"}/
        %ul.app__banner__icon__store
          %li.app__banner__icon__store-app
            = link_to image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?4194600336"), 'https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8', class:"app__banner__icon__store-app-link"
          %li.app__banner__icon__store-app
            = link_to image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?4194600336"), 'https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja', class:"app__banner__icon__store-app-link"

%footer.footer
  .footer__nav
    .footer__nav__aboutMercari
      %h2.footer__nav-title
        メルカリについて
      %ul
        %li.footer-item
          会社概要(運営会社)
        %li.footer-item
          採用情報
        %li.footer-item
          プレスリリース
        %li.footer-item
          公式ブログ
        %li.footer-item
          メルカリロゴ利用ガイドライン
          %li.footer-item.font__icon
            %i.fa.fa-twitter.i
          %li.footer-item.font__icon
            %i.fa.fa-facebook-official.i

    .footer__nav__helpGuide
      %h2.footer__nav-title
        ヘルプ&ガイド
      %ul
        %li.footer-item
          メルカリガイド
        %li.footer-item
          らくらくメルカリ便
        %li.footer-item
          ゆうゆうメルカリ便
        %li.footer-item
          大型メルカリ便
        %li.footer-item
          車体取引ガイド
        %li.footer-item
          メルカリあんしん・あんぜん宣言！
        %li.footer-item
          偽ブランド品撲滅への取り組み
        %li.footer-item
          メルカリボックス

    .footer__nav__privacy
      %h2.footer__nav-title
        プライバシーと利用規約
      .footer__nav__privacy-inner
        %ul
          %li.footer-item
            プライバシポリシー
          %li.footer-item
            メルカリ利用規約
          %li.footer-item
            あんしんスマホサポート制度に関する利用規約
          %li.footer-item
            コンプライアンスポリシー
      .footer__nav__privacy-inner
        %ul
          %li.footer-item
            個人データの安全管理に係る基本方針
          %li.footer-item
            特定商取引に関する表記
          %li.footer-item
            資金決済法に基づく表示
          %li.footer-item
            法令厳守と犯罪防止のために
          %li.footer-item
            返品・返金ポリシー

    .footer__nav__country
      %h2.footer__nav-title
        国
      %ul
        %li.footer-item
          日本
        %li.footer-item
          United States

  .footer__bottom
    = link_to image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?4194600336"), root_path, class:"footer__bottom-logo"
    %span.footer__bottom-copyright
      © 2019 Mercari

app/views/layouts/_header.html.haml
%header.header
  .header__contents
    .header__contents__ber
      = link_to image_tag("logo.png"), root_path, class:"header__contents__ber-logo"
      .header__contents__ber-search
        = form_tag root_path, method: :get, class: "header__contents__ber__search__form" do
          = text_field_tag :keyword, '', class: 'search__box-text', placeholder: '何かお探しですか？'
        %i.fa.fa-search.font-search
    .header__contents__nav
      .header__contents__nav__left
        %a.header__contents__nav__left-category{href: root_path}
          %i.fa.fa-list.header__contents__nav__left-category-icon
          .header__contents__nav__left-category-text
            カテゴリーから探す
        %ul.header__contents__nav__left-categories
          - @categories.each do |category|
            %li.header__contents__nav__left-categories-list
              = category.name
              -# %ul.level-2
              -#   - category.children.each do |child|
              -#     %li.level-2__list
              -#       = child.name
              -#       %ul.level-3
              -#         - child.children.each do |grandchild|
              -#           %li.level-3__list
              -#             = grandchild.name

        %a.header__contents__nav__left-brand{href: root_path}
          %i.fa.fa-tag.header__contents__nav__left-brand-icon
          .header__contents__nav__left-brand-text
            ブランドから探す
        %ul.header__contents__nav__left-brands
          %li.header__contents__nav__left-brands-list
            シャネル
          %li.header__contents__nav__left-brands-list
            ナイキ
          %li.header__contents__nav__left-brands-list
            ルイ ヴィトン
          %li.header__contents__nav__left-brands-list
            シュプリーム
          %li.header__contents__nav__left-brands-list
            アディダス
          %li.header__contents__nav__left-brands-list
            ブランド一覧

      .header__contents__nav__right
        -if user_signed_in?
          %a.header__contents__nav__right-notifications
            %i.fa.fa-bell-o.icon
            お知らせ
          %a.header__contents__nav__right-todo
            %i.fa.fa-check.icon
            やることリスト
          %a.header__contents__nav__right-mypage{href: user_path(current_user.id)}
            %img.header__contents__nav__right-mypage-img{src: "https://static.mercdn.net/images/member_photo_noimage_thumb.png"}/            
            マイページ
        -else
          = link_to "ログイン", new_user_session_path, class: "btn btn-red header__contents__nav__right-login"
          = link_to "新規会員登録",  new_user_path, class: "btn btn-signup header__contents__nav__right-register"

app/views/layouts/_session-footer.html.haml
.solo-footer
  %nav
    %ul
      %li
        ="プライバシーポリシー"
      %li
        ="メルカリ利用規約"
      %li
        ="特定商取引に関する表記"
  .solo-footer-logo
    = link_to image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg", alt: "mercari"), :back, class: 'hooter-image'
  %p
    ="© 2019 Mercari"

app/views/layouts/_session-header.html.haml
.solo-header
  .logo
    = link_to image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg", alt: "mercari"), :back, class: 'session-home'

app/views/layouts/_sidemenu.html.haml
.side
  .mypage-navi
    .mypage-navi-list
      %ul
        %li
          %a
            ="お知らせ"
            %i.fa.fa-angle-right
        %li
          %a
            ="やることリスト"
            %i.fa.fa-angle-right
        %li
          %a
            ="いいね！一覧"
            %i.fa.fa-angle-right
        %li
          %a
            ="出品する"
            %i.fa.fa-angle-right
        %li
          = link_to listings_path do
            ="出品した商品 - 出品中"
            %i.fa.fa-angle-right
        %li
          = link_to in_progress_listings_path do
            ="出品した商品 - 取引中"
            %i.fa.fa-angle-right
        %li
          = link_to completed_listings_path do
            ="出品した商品 - 売却済み"
            %i.fa.fa-angle-right
        %li
          = link_to purchase_listings_path do
            ="購入した商品 - 取引中"
            %i.fa.fa-angle-right
        %li
          = link_to purchased_listings_path do
            ="購入した商品 - 過去の取引"
            %i.fa.fa-angle-right
        %li
          %a
            ="ニュース一覧"
            %i.fa.fa-angle-right
        %li
          %a
            ="評価一覧"
            %i.fa.fa-angle-right
        %li
          %a
            ="ガイド"
            %i.fa.fa-angle-right
        %li
          %a
            ="お問い合わせ"
            %i.fa.fa-angle-right
    .mypage-navi-head
      %h3
        ="メルペイ"
    .mypage-navi-list
      %ul
        %li
          %a
            ="売上・振込申請"
            %i.fa.fa-angle-right
        %li
          %a
            ="ポイント"
            %i.fa.fa-angle-right
    .mypage-navi-head
      %h3
        ="設定"
    .mypage-navi-list
      %ul
        %li
          %a
            ="プロフィール"
            %i.fa.fa-angle-right
        %li
          %a
            ="発送元・お届け先住所変更"
            %i.fa.fa-angle-right
        %li
          = link_to user_card_infos_path(current_user.id) do
            支払い方法
            %i.fa.fa-angle-right
        %li
          %a
            ="メール/パスワード"
            %i.fa.fa-angle-right
        %li
          %a
            ="本人情報"
            %i.fa.fa-angle-right
        %li
          %a
            ="電話番号の確認"
            %i.fa.fa-angle-right
        %li
          = link_to logout_path do
            ログアウト
            %i.fa.fa-angle-right

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample50b
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield